name: CI - Build and Test Spring Boot App with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test with Gradle
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALLDATA_TOKEN }}
          JWT_SECRET_KEY_SOCCER_GENIUS: ${{ secrets.JWT_SECRET_KEY_SOCCER_GENIUS }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: ./gradlew test
      - name: SonarCloud Scan with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
